### PR TITLE
fix a threefry overflow

### PR DESCRIPTION
**Pull request by rurban**
we only have N steps.

This bug is not upstream, in Random123.

### CODE REVIEW

**Comment by bashtage** [comment]
Thanks, and thanks for checking philox. Should be more shared code but refactoring is rarely enjoyable.  I'll take a look a bit later, and see what I can see about the CI.

**Comment by bashtage** [comment]
I don't fully see the problem.  This is the idea.  Suppose we are using a 64x4 generator, and we have a step size of 2**65.  This will be represented as `[0x0 0x1 0x0 0x0]` at the start of the function.  This issue occurs since each increment of the counter adds 4 values, so we need to transform this to be `[0x8000000000000000 0 0 0]`, which is `[2**63 0 0 0]`.  The for each of the paired values, this is done by taking the mod of the lower one and then adding the lower bits of the upper one. So `step[i + 1] % N` is grabbing the lower bits.

Maybe I'm not awake yet, but this seems right.  Can you help me understand the need for a fix?

**Comment by bashtage** [comment]
The mod here could have been done with right shift then a left shift.  The mod was just easier.

**Comment by rurban** [comment]
`step[i + 1] % N` accesses step[N] out of bounds in the last loop instance.
`step[(i + 1 % N)]` wraps the index around from N to 0. asan finds this bug.

**Comment by bashtage** [comment]
I see. But that is the wrong fix.  Could just ad an 

```c
if (i < N) {
    ...
}
```

to protect [i+1] from ever going out of bounds.  The `% N` in the expression is essential for a correct calculation. There is no need to wrap since the final calculation when i == N-1 isn't needed.

**Comment by rurban** [comment]
I see, will do.

Another problem: When I checked it again, I saw that steps[] are never initialized. These are stack values, so random.

**Comment by bashtage** [comment]
@rurban I went ahead and fixed the overflow.  I didn't port over any of the optimizations. Do they make much difference?

**Comment by rurban** [comment]
The optimizations are only for the seed step. But with large seed numbers they do make a difference, yes.
In my use-case, dieharder, I do a lot of seed calls.

**Pull request closed without merging**
